version: '3'

services:
  db:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_file_format=Barracuda --innodb_file_per_table=1 --innodb_large_prefix --explicit_defaults_for_timestamp=1 --sql_mode=STRICT_TRANS_TABLES
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_DATABASE=development
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3308:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
  web:
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-tutorial:/code
    ports:
      - "8002:8000"
    depends_on:
      - db
